In [1]:
import kagglehub

# Download latest version
path = kagglehub.competition_download('store-sales-time-series-forecasting')

print("Path to competition files:", path)

c:\Users\DYNABOOK\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to competition files: C:\Users\DYNABOOK\.cache\kagglehub\competitions\store-sales-time-series-forecasting

In [2]:
import pandas as pd

path = r"C:\Users\DYNABOOK\.cache\kagglehub\competitions\store-sales-time-series-forecasting"

train = pd.read_csv(f"{path}/train.csv")
test = pd.read_csv(f"{path}/test.csv")
stores = pd.read_csv(f"{path}/stores.csv")
oil = pd.read_csv(f"{path}/oil.csv")
holidays = pd.read_csv(f"{path}/holidays_events.csv")
transactions = pd.read_csv(f"{path}/transactions.csv")

print("train:", train.shape)
print("test:", test.shape)
print("stores:", stores.shape)
print("oil:", oil.shape)
print("holidays:", holidays.shape)
print("transactions:", transactions.shape)

train: (3000888, 6)
test: (28512, 5)
stores: (54, 5)
oil: (1218, 2)
holidays: (350, 6)
transactions: (83488, 3)

In [3]:
train.info()
train.describe()
train.head()

<class 'pandas.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         str
 2   store_nbr    int64
 3   family       str
 4   sales        float64
 5   onpromotion  int64
dtypes: float64(1), int64(3), str(2)
memory usage: 137.4 MB

   id        date  store_nbr      family  sales  onpromotion
0   0  2013-01-01          1  AUTOMOTIVE    0.0            0
1   1  2013-01-01          1   BABY CARE    0.0            0
2   2  2013-01-01          1      BEAUTY    0.0            0
3   3  2013-01-01          1   BEVERAGES    0.0            0
4   4  2013-01-01          1       BOOKS    0.0            0

In [4]:
train.sample(5, random_state=42)
train.tail()

,id,date,store_nbr,family,sales,onpromotion
3000883,3000883,2017-08-15,9,POULTRY,438.133,0
3000884,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
3000885,3000885,2017-08-15,9,PRODUCE,2419.729,148
3000886,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
3000887,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [5]:
train['date'] = pd.to_datetime(train['date'])

In [6]:
test.info()
test.describe()
test['date'] = pd.to_datetime(test['date'])

<class 'pandas.DataFrame'>
RangeIndex: 28512 entries, 0 to 28511
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           28512 non-null  int64
 1   date         28512 non-null  str
 2   store_nbr    28512 non-null  int64
 3   family       28512 non-null  str
 4   onpromotion  28512 non-null  int64
dtypes: int64(3), str(2)
memory usage: 1.1 MB

In [7]:
stores.info()
# stores.describe()
# stores.head()
# stores.sample(5, random_state=42)
# stores.columns
stores.shape

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   store_nbr  54 non-null     int64
 1   city       54 non-null     str
 2   state      54 non-null     str
 3   type       54 non-null     str
 4   cluster    54 non-null     int64
dtypes: int64(2), str(3)
memory usage: 2.2 KB

(54, 5)

In [8]:
# oil.describe()
# oil.head()
# oil.sample(5, random_state=42)
# oil.columns
oil.info()
oil['date'] = pd.to_datetime(oil['date'])
oil.shape

<class 'pandas.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   str
 1   dcoilwtico  1175 non-null   float64
dtypes: float64(1), str(1)
memory usage: 19.2 KB

(1218, 2)

In [9]:
# holidays.describe()
holidays.info()
holidays.sample(5, random_state=42)
# holidays.columns

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    str
 1   type         350 non-null    str
 2   locale       350 non-null    str
 3   locale_name  350 non-null    str
 4   description  350 non-null    str
 5   transferred  350 non-null    bool
dtypes: bool(1), str(5)
memory usage: 14.1 KB

,date,type,locale,locale_name,description,transferred
157,2014-12-26,Additional,National,Ecuador,Navidad+1,False
341,2017-12-08,Holiday,Local,Loja,Fundacion de Loja,False
315,2017-06-25,Holiday,Regional,Imbabura,Provincializacion de Imbabura,False
234,2016-04-30,Event,National,Ecuador,Terremoto Manabi+14,False
155,2014-12-25,Holiday,National,Ecuador,Navidad,False

In [10]:
holidays['date'] = pd.to_datetime(holidays['date'])

In [11]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  str
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), str(1)
memory usage: 1.9 MB

In [12]:
transactions['date'] = pd.to_datetime(transactions['date'])

In [13]:
print(oil['date'].dtype)
print(holidays['date'].dtype)
print(transactions['date'].dtype)
print(train['date'].dtype)
print(test['date'].dtype)

datetime64[us]
datetime64[us]
datetime64[us]
datetime64[us]
datetime64[us]

In [14]:
train = train.merge(stores, on='store_nbr', how='left')
test = test.merge(stores, on='store_nbr', how='left')

print(train.shape)
print(train.head())

(3000888, 10)
   id       date  store_nbr      family  sales  onpromotion   city      state  \
0   0 2013-01-01          1  AUTOMOTIVE    0.0            0  Quito  Pichincha
1   1 2013-01-01          1   BABY CARE    0.0            0  Quito  Pichincha
2   2 2013-01-01          1      BEAUTY    0.0            0  Quito  Pichincha
3   3 2013-01-01          1   BEVERAGES    0.0            0  Quito  Pichincha
4   4 2013-01-01          1       BOOKS    0.0            0  Quito  Pichincha

  type  cluster
0    D       13
1    D       13
2    D       13
3    D       13
4    D       13

In [15]:
train.columns

Index(['id', 'date', 'store_nbr', 'family', 'sales', 'onpromotion', 'city',
       'state', 'type', 'cluster'],
      dtype='str')

In [16]:
test.columns
test.shape

(28512, 9)

In [17]:
print(train.isna().sum())

id             0
date           0
store_nbr      0
family         0
sales          0
onpromotion    0
city           0
state          0
type           0
cluster        0
dtype: int64

In [18]:
train = train.merge(oil, on='date', how='left')
test = test.merge(oil, on='date', how='left')

print(train.shape)
# print(train[['date', 'dcoilwtico']].head())

(3000888, 11)

In [19]:
print(test.shape)
print(test[['date', 'dcoilwtico']].head())

(28512, 10)
        date  dcoilwtico
0 2017-08-16        46.8
1 2017-08-16        46.8
2 2017-08-16        46.8
3 2017-08-16        46.8
4 2017-08-16        46.8

In [20]:
print(test['dcoilwtico'].isna().sum())

7128

In [21]:
# How many unique dates does train have vs oil?
print("Unique dates in train:", train['date'].nunique())
print("Unique dates in oil:", oil['date'].nunique())

# Which dates exist in train but NOT in oil at all?
train_dates = set(train['date'].unique())
oil_dates = set(oil['date'].unique())

missing_dates = train_dates - oil_dates
print("Dates in train with NO oil price at all:", len(missing_dates))

Unique dates in train: 1684
Unique dates in oil: 1218
Dates in train with NO oil price at all: 481

In [22]:
train = train.sort_values('date').reset_index(drop=True)
train['dcoilwtico'] = train['dcoilwtico'].ffill()

test = test.sort_values('date').reset_index(drop=True)
test['dcoilwtico'] = test['dcoilwtico'].ffill()

print(train['dcoilwtico'].isna().sum())
print(test['dcoilwtico'].isna().sum())

1782
0

In [23]:
print(train[train['dcoilwtico'].isna()]['date'].min())
print(train[train['dcoilwtico'].isna()]['date'].max())

2013-01-01 00:00:00
2013-01-01 00:00:00

In [24]:
train['dcoilwtico'] = train['dcoilwtico'].bfill()

print(train['dcoilwtico'].isna().sum())

0

In [25]:
train.head(5)
train.tail(5)
train.sample(5, random_state=42)

,id,date,store_nbr,family,sales,onpromotion,city,state,type,cluster,dcoilwtico
2483653,2482471,2016-10-28,13,GROCERY II,5.0,0,Latacunga,Cotopaxi,C,15,48.72
2761877,2760985,2017-04-03,28,CLEANING,1525.0,29,Guayaquil,Guayas,E,10,50.25
1217988,1218589,2014-11-16,5,SCHOOL AND OFFICE SUPPLIES,0.0,0,Santo Domingo,Santo Domingo de los Tsachilas,D,4,75.91
1231938,1233095,2014-11-24,8,HOME APPLIANCES,0.0,0,Quito,Pichincha,D,8,75.74
528175,528912,2013-10-24,49,LINGERIE,4.0,0,Quito,Pichincha,A,11,96.65

In [26]:
print(holidays['date'].duplicated().sum())
train['family'].value_counts

38

<bound method IndexOpsMixin.value_counts of 0             AUTOMOTIVE
1            CELEBRATION
2           BREAD/BAKERY
3                  BOOKS
4              BEVERAGES
               ...
3000883     PET SUPPLIES
3000884    PERSONAL CARE
3000885            MEATS
3000886           BEAUTY
3000887          SEAFOOD
Name: family, Length: 3000888, dtype: str>

In [27]:
print(holidays['transferred'].value_counts())

transferred
False    338
True      12
Name: count, dtype: int64

In [28]:
holidays.head(5)

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [29]:
holidays_clean = holidays[holidays['transferred'] == False].copy()

In [30]:
holiday_dates = holidays_clean[['date']].drop_duplicates()
holiday_dates['is_holiday'] = 1

train = train.merge(holiday_dates, on='date', how='left')
test = test.merge(holiday_dates, on='date', how='left')

train['is_holiday'] = train['is_holiday'].fillna(0).astype(int)
test['is_holiday'] = test['is_holiday'].fillna(0).astype(int)

print(train['is_holiday'].value_counts())
print(test['is_holiday'].value_counts())

is_holiday
0    2567862
1     433026
Name: count, dtype: int64
is_holiday
0    26730
1     1782
Name: count, dtype: int64

In [31]:
train.head(5)

,id,date,store_nbr,family,sales,onpromotion,city,state,type,cluster,dcoilwtico,is_holiday
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,Quito,Pichincha,D,13,93.14,1
1,1194,2013-01-01,42,CELEBRATION,0.0,0,Cuenca,Azuay,D,2,93.14,1
2,1193,2013-01-01,42,BREAD/BAKERY,0.0,0,Cuenca,Azuay,D,2,93.14,1
3,1192,2013-01-01,42,BOOKS,0.0,0,Cuenca,Azuay,D,2,93.14,1
4,1191,2013-01-01,42,BEVERAGES,0.0,0,Cuenca,Azuay,D,2,93.14,1

In [32]:
# ============================================
# Merge transactions into TRAIN only (for EDA/comparison purposes)
# NOT merged into test — it doesn't exist for future dates
# ============================================

train = train.merge(transactions, on=['date', 'store_nbr'], how='left')

print("Missing transactions in train:", train['transactions'].isna().sum())
print("Missing transactions %:", train['transactions'].isna().mean())

# Fill missing transactions (only within train) using median
# Median is safer than mean here since transaction counts can have outlier spikes
train['transactions'] = train['transactions'].fillna(train['transactions'].median())

print("After fill, missing transactions in train:", train['transactions'].isna().sum())

Missing transactions in train: 245784
Missing transactions %: 0.08190375648807953
After fill, missing transactions in train: 0

In [33]:
# ============================================
# Date-based feature engineering
# Apply identically to train AND test
# ============================================

for df in [train, test]:
    df['year'] = df['date'].dt.year
    df['month'] = df['date'].dt.month
    df['day'] = df['date'].dt.day
    df['day_of_week'] = df['date'].dt.dayofweek      # 0=Monday, 6=Sunday
    df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)
    df['week_of_year'] = df['date'].dt.isocalendar().week.astype(int)
    df['quarter'] = df['date'].dt.quarter
    df['is_month_start'] = df['date'].dt.is_month_start.astype(int)
    df['is_month_end'] = df['date'].dt.is_month_end.astype(int)

print(train[['date', 'year', 'month', 'day', 'day_of_week', 'is_weekend', 'week_of_year', 'quarter']].head())

        date  year  month  day  day_of_week  is_weekend  week_of_year  quarter
0 2013-01-01  2013      1    1            1           0             1        1
1 2013-01-01  2013      1    1            1           0             1        1
2 2013-01-01  2013      1    1            1           0             1        1
3 2013-01-01  2013      1    1            1           0             1        1
4 2013-01-01  2013      1    1            1           0             1        1

In [34]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 22 columns):
 #   Column          Dtype
---  ------          -----
 0   id              int64
 1   date            datetime64[us]
 2   store_nbr       int64
 3   family          str
 4   sales           float64
 5   onpromotion     int64
 6   city            str
 7   state           str
 8   type            str
 9   cluster         int64
 10  dcoilwtico      float64
 11  is_holiday      int64
 12  transactions    float64
 13  year            int32
 14  month           int32
 15  day             int32
 16  day_of_week     int32
 17  is_weekend      int64
 18  week_of_year    int64
 19  quarter         int32
 20  is_month_start  int64
 21  is_month_end    int64
dtypes: datetime64[us](1), float64(3), int32(5), int64(9), str(4)
memory usage: 446.5 MB

In [35]:
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 28512 entries, 0 to 28511
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              28512 non-null  int64
 1   date            28512 non-null  datetime64[us]
 2   store_nbr       28512 non-null  int64
 3   family          28512 non-null  str
 4   onpromotion     28512 non-null  int64
 5   city            28512 non-null  str
 6   state           28512 non-null  str
 7   type            28512 non-null  str
 8   cluster         28512 non-null  int64
 9   dcoilwtico      28512 non-null  float64
 10  is_holiday      28512 non-null  int64
 11  year            28512 non-null  int32
 12  month           28512 non-null  int32
 13  day             28512 non-null  int32
 14  day_of_week     28512 non-null  int32
 15  is_weekend      28512 non-null  int64
 16  week_of_year    28512 non-null  int64
 17  quarter         28512 non-null  int32
 18  is_month_start  28512 non-null  int64
 19  is_month_end    28512 non-null  int64
dtypes: datetime64[us](1), float64(1), int32(5), int64(9), str(4)
memory usage: 3.8 MB

In [36]:
train.isna().sum()

id                0
date              0
store_nbr         0
family            0
sales             0
onpromotion       0
city              0
state             0
type              0
cluster           0
dcoilwtico        0
is_holiday        0
transactions      0
year              0
month             0
day               0
day_of_week       0
is_weekend        0
week_of_year      0
quarter           0
is_month_start    0
is_month_end      0
dtype: int64

In [37]:
train.columns

Index(['id', 'date', 'store_nbr', 'family', 'sales', 'onpromotion', 'city',
       'state', 'type', 'cluster', 'dcoilwtico', 'is_holiday', 'transactions',
       'year', 'month', 'day', 'day_of_week', 'is_weekend', 'week_of_year',
       'quarter', 'is_month_start', 'is_month_end'],
      dtype='str')

In [38]:
df.dtypes

id                         int64
date              datetime64[us]
store_nbr                  int64
family                       str
onpromotion                int64
city                         str
state                        str
type                         str
cluster                    int64
dcoilwtico               float64
is_holiday                 int64
year                       int32
month                      int32
day                        int32
day_of_week                int32
is_weekend                 int64
week_of_year               int64
quarter                    int32
is_month_start             int64
is_month_end               int64
dtype: object

In [39]:
train.describe()

,id,date,store_nbr,sales,onpromotion,cluster,dcoilwtico,is_holiday,transactions,year,month,day,day_of_week,is_weekend,week_of_year,quarter,is_month_start,is_month_end
count,3.000888e+06,3000888,3.000888e+06,3.000888e+06,3.000888e+06,3.000888e+06,3.000888e+06,3.000888e+06,3.000888e+06,3.000888e+06,3.000888e+06,3.000888e+06,3.000888e+06,3.000888e+06,3.000888e+06,3.000888e+06,3.000888e+06,3.000888e+06
mean,1.500444e+06,2015-04-24 08:27:04.703088,2.750000e+01,3.577757e+02,2.602770e+00,8.481481e+00,6.792490e+01,1.442993e-01,1.669900e+03,2.014838e+03,6.207838e+00,1.563005e+01,2.997031e+00,2.856295e-01,2.524287e+01,2.410333e+00,3.325416e-02,3.266033e-02
min,0.000000e+00,2013-01-01 00:00:00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,2.619000e+01,0.000000e+00,5.000000e+00,2.013000e+03,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00
25%,7.502218e+05,2014-02-26 18:00:00,1.400000e+01,0.000000e+00,0.000000e+00,4.000000e+00,4.637750e+01,0.000000e+00,1.083000e+03,2.014000e+03,3.000000e+00,8.000000e+00,1.000000e+00,0.000000e+00,1.300000e+01,1.000000e+00,0.000000e+00,0.000000e+00
50%,1.500444e+06,2015-04-24 12:00:00,2.750000e+01,1.100000e+01,0.000000e+00,8.500000e+00,5.341000e+01,0.000000e+00,1.393000e+03,2.015000e+03,6.000000e+00,1.600000e+01,3.000000e+00,0.000000e+00,2.500000e+01,2.000000e+00,0.000000e+00,0.000000e+00
75%,2.250665e+06,2016-06-19 06:00:00,4.100000e+01,1.958473e+02,0.000000e+00,1.300000e+01,9.572000e+01,0.000000e+00,1.976250e+03,2.016000e+03,9.000000e+00,2.300000e+01,5.000000e+00,1.000000e+00,3.800000e+01,3.000000e+00,0.000000e+00,0.000000e+00
max,3.000887e+06,2017-08-15 00:00:00,5.400000e+01,1.247170e+05,7.410000e+02,1.700000e+01,1.106200e+02,1.000000e+00,8.359000e+03,2.017000e+03,1.200000e+01,3.100000e+01,6.000000e+00,1.000000e+00,5.300000e+01,4.000000e+00,1.000000e+00,1.000000e+00
std,8.662819e+05,NaN,1.558579e+01,1.101998e+03,1.221888e+01,4.649735e+00,2.566913e+01,3.513930e-01,9.266882e+02,1.345518e+00,3.385668e+00,8.794789e+00,2.000740e+00,4.517138e-01,1.479467e+01,1.099952e+00,1.792995e-01,1.777460e-01

In [40]:


X = train.drop(columns=['id', 'sales', 'date'])
y = train['sales']

print(X.shape)
print(y.shape)
print(X.columns.tolist())

(3000888, 19)
(3000888,)
['store_nbr', 'family', 'onpromotion', 'city', 'state', 'type', 'cluster', 'dcoilwtico', 'is_holiday', 'transactions', 'year', 'month', 'day', 'day_of_week', 'is_weekend', 'week_of_year', 'quarter', 'is_month_start', 'is_month_end']

In [41]:
dates = train['date']   # keep this handy for the split step

In [42]:
cutoff_date = dates.max() - pd.Timedelta(days=60)

train_mask = dates <= cutoff_date
test_mask = dates > cutoff_date

X_train, y_train = X[train_mask], y[train_mask]
X_test, y_test = X[test_mask], y[test_mask]

print("X_train:", X_train.shape, "y_train:", y_train.shape)
print("X_test:", X_test.shape, "y_test:", y_test.shape)

X_train: (2893968, 19) y_train: (2893968,)
X_test: (106920, 19) y_test: (106920,)

In [ ]:


categorical_cols = ['family', 'city', 'state', 'type']
numeric_cols = ['store_nbr', 'onpromotion', 'dcoilwtico', 'is_holiday', 'cluster',
                 'year', 'month', 'day', 'day_of_week', 'is_weekend',
                 'week_of_year', 'quarter', 'is_month_start', 'is_month_end']

# Rebuild X and y fresh (using the original train, not the one-hot encoded version)
X = train[numeric_cols + categorical_cols].copy()
y = train['sales']
dates = train['date']

# Convert categorical columns to pandas 'category' dtype — LightGBM handles this natively
for col in categorical_cols:
    X[col] = X[col].astype('category')

print(X.shape)
print(X.dtypes)

(3000888, 18)
store_nbr            int64
onpromotion          int64
dcoilwtico         float64
is_holiday           int64
cluster              int64
year                 int32
month                int32
day                  int32
day_of_week          int32
is_weekend           int64
week_of_year         int64
quarter              int32
is_month_start       int64
is_month_end         int64
family            category
city              category
state             category
type              category
dtype: object

In [46]:
cutoff_date = dates.max() - pd.Timedelta(days=60)

train_mask = dates <= cutoff_date
test_mask = dates > cutoff_date

X_train, y_train = X[train_mask], y[train_mask]
X_test, y_test = X[test_mask], y[test_mask]

print("X_train:", X_train.shape, "y_train:", y_train.shape)
print("X_test:", X_test.shape, "y_test:", y_test.shape)

X_train: (2893968, 18) y_train: (2893968,)
X_test: (106920, 18) y_test: (106920,)

In [47]:
import numpy as np

y_train_log = np.log1p(y_train)   # log(1 + sales) — handles sales=0 safely

In [48]:
import lightgbm as lgb
from sklearn.metrics import mean_squared_log_error
import time

start = time.time()

model = lgb.LGBMRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=-1,        # let it grow naturally, no artificial cap this time
    num_leaves=63,
    random_state=42
)

model.fit(
    X_train, y_train_log,
    categorical_feature=categorical_cols
)

print(f"Training took {time.time() - start:.1f} seconds")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.074295 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 734
[LightGBM] [Info] Number of data points in the train set: 2893968, number of used features: 18
[LightGBM] [Info] Start training from score 2.900895
Training took 11.2 seconds

In [49]:
y_pred_log = model.predict(X_test)
y_pred = np.expm1(y_pred_log)          # reverse log1p
y_pred = np.clip(y_pred, 0, None)      # sales can't be negative

rmsle = np.sqrt(mean_squared_log_error(y_test, y_pred))
print("Test RMSLE:", rmsle)

# Also check train performance
y_train_pred = np.clip(np.expm1(model.predict(X_train)), 0, None)
train_rmsle = np.sqrt(mean_squared_log_error(y_train, y_train_pred))
print("Train RMSLE:", train_rmsle)

Test RMSLE: 0.4963892735531427
Train RMSLE: 0.5012354418971521

In [50]:
# Combine train_split + test_split back into the full set
X_full = X  # the complete X we built before splitting
y_full_log = np.log1p(y)  # log-transform the full target

model_final = lgb.LGBMRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=-1,
    num_leaves=63,
    random_state=42
)

model_final.fit(X_full, y_full_log, categorical_feature=categorical_cols)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.065857 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 739
[LightGBM] [Info] Number of data points in the train set: 3000888, number of used features: 18
[LightGBM] [Info] Start training from score 2.926368

LGBMRegressor(learning_rate=0.05, n_estimators=300, num_leaves=63,
              random_state=42)

In [51]:
X_submit = test[numeric_cols + categorical_cols].copy()

for col in categorical_cols:
    X_submit[col] = X_submit[col].astype('category')

print(X_submit.shape)
print(X_submit.dtypes)

(28512, 18)
store_nbr            int64
onpromotion          int64
dcoilwtico         float64
is_holiday           int64
cluster              int64
year                 int32
month                int32
day                  int32
day_of_week          int32
is_weekend           int64
week_of_year         int64
quarter              int32
is_month_start       int64
is_month_end         int64
family            category
city              category
state             category
type              category
dtype: object

In [52]:
y_submit_log = model_final.predict(X_submit)
y_submit = np.expm1(y_submit_log)       # reverse log1p
y_submit = np.clip(y_submit, 0, None)   # sales can't be negative

In [53]:
submission = pd.DataFrame({
    'id': test['id'],
    'sales': y_submit
})

print(submission.head())
print(submission.shape)   # should match test.csv's row count exactly

        id        sales
0  3000888     3.537641
1  3002082     9.819017
2  3002081   495.429972
3  3002080     0.173139
4  3002079  2128.134337
(28512, 2)

In [54]:
submission.to_csv('submission.csv', index=False)